=== Hrijon/node-xml/lab6/course.xsd
<?xml version="1.0" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <!-- SIMPLE ELEMENTS -->

    <xsd:element name="name" type="xsd:string"/>
    <xsd:element name="title" type="xsd:string"/>
    <xsd:element name="email" type="xsd:string"/>
    <xsd:element name="surname" type="xsd:string"/>
    <xsd:element name="othernames" type="xsd:string"/>
    
    <!-- COMPLEX ELEMENTS -->

    <xsd:element name="course">
        <xsd:complexType>
            <xsd:sequence>
              <xsd:element ref="name" />
              <xsd:element ref="unit" minOccurs="0" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="unit">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="title" />
                <xsd:element ref="lecturer" minOccurs="0" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="lecturer">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="surname" />
                <xsd:element ref="othernames" minOccurs="0" maxOccurs="1"/>
                <xsd:element ref="email" minOccurs="0" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

</xsd:schema>

=== Hrijon/node-xml/lab6/course-validxsd.xml
<?xml version="1.0"?>

<course xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:noNamespaceSchemaLocation="course.xsd">
	<name>Bachelor of Science - Internet Computing. list of units</name>
	
	<unit>
		<title>ICT375 Advanced Web Programming</title>
		<lecturer>
			<surname>Xie</surname>
			<othernames>Hong</othernames>
			<email>H.Xie@murdoch.edu.au</email>
		</lecturer>
	</unit>
	<unit>
		<title>ICT108 Introduction to Multimedia and the Internet</title>
		<lecturer>
			<surname>Rai</surname>
			<othernames>Shri</othernames>
			<email>s.rai@murdoch.edu.au</email>
		</lecturer>
	</unit>
    <unit>
		<title>ICT302 IT Project</title>
		<lecturer>
			<surname>Cole</surname>
			<othernames>Peter</othernames>
			<semester>1</semester>
		</lecturer>
	</unit>
</course>
